server:
  port: 8080
spring:
  application:
    name: user-authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdetails
    username: root
    password: Pass@123
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

